services:
  jangrobby:
    build: .
    shm_size: 6gb
    ports:
      - "80:80"
  jangrobby1:
    build: .
    shm_size: 6gb
    ports:
      - "80:80"
  jangrobby2:
    build: .
    shm_size: 6gb
    ports:
      - "80:80"
  jangrobby3:
    build: .
    shm_size: 6gb
    ports:
      - "80:80"
  jangrobby4:
    build: .
    shm_size: 6gb
    ports:
      - "80:80"
  jangrobby5:
    build: .
    shm_size: 6gb
    ports:
      - "80:80"
  jangrobby6:
    build: .
    shm_size: 6gb
    ports:
      - "80:80"
  jangrobby7:
    build: .
    shm_size: 6gb
    ports:
      - "80:80"
  jangrobby8:
    build: .
    shm_size: 6gb
    ports:
      - "80:80"
  jangrobby9:
    build: .
    shm_size: 6gb
    ports:
      - "80:80"
  jangrobby10:
    build: .
    shm_size: 6gb
    ports:
      - "80:80"
  jangrobby11:
    build: .
    shm_size: 6gb
    ports:
      - "80:80"
  jangrobby12:
    build: .
    shm_size: 6gb
    ports:
      - "80:80"
  jangrobby13:
    build: .
    shm_size: 6gb
    ports:
      - "80:80"
  jangrobby14:
    build: .
    shm_size: 6gb
    ports:
      - "80:80"
  jangrobby15:
    build: .
    shm_size: 6gb
    ports:
      - "80:80"
  jangrobby16:
    build: .
    shm_size: 6gb
    ports:
      - "80:80"
  jangrobby17:
    build: .
    shm_size: 6gb
    ports:
      - "80:80"
  jangrobby18:
    build: .
    shm_size: 6gb
    ports:
      - "80:80"
  jangrobby19:
    build: .
    shm_size: 6gb
    ports:
      - "80:80"
